FEATURE added pickFlowersFromPots rule.
Gilly7CE/Carpet-Addons-Not-Found pull request #117
Opened 2023-05-27 09:43 UTC by Serzbiedry

Injects into FlowerPotBlock.onUse at tail, essentially making another case for interaction.

2023-05-27 12:29 UTC, Basicprogrammer10 requested changes

2023-05-27 12:29 UTC, Basicprogrammer10 commented on src/main/java/gillycarpetaddons/mixins/FlowerPotBlock_pickFlowersFromPots.java
> +      cir.setReturnValue(ActionResult.CONSUME);
Setting a return value cancels the function already.

2023-05-27 12:29 UTC, Basicprogrammer10 commented on src/main/java/gillycarpetaddons/mixins/FlowerPotBlock_pickFlowersFromPots.java
> +                  shift = At.Shift.BEFORE
I'm not sure if this shift is needed.

2023-05-27 14:00 UTC, Gilly7CE requested changes
Couple of things to address. The merge conflicts you’re going to need to resolve is not nice either.

2023-05-27 14:01 UTC, Gilly7CE commented on src/main/resources/assets/gilly7ce-carpet-addons/lang/en_us.json
> +  "carpet.rule.pickFlowersFromPots.desc": "Right-clicking on a flowerpot with a flower in it will put the flower into your invantory",
This also makes me think is “pick” the right name now?

2023-05-29 19:34 UTC, Gilly7CE commented
As discussed on discord, abandoning the PR as the merge conflicts are problematic and it is easier to just start from scratch using this as a reference.

2023-05-29 19:34 UTC, closed without merging